language: python
python:
    - 3.6
# command to install dependencies
install:
  - pip install howlongtobeatpy
  - pip install nose
  - pip install codecov
# command to run tests
script:
  - nosetests howlongtobeatpy --with-coverage
after_success:
  - codecov
