# This workflows will test the released version of the API

name: Python Test

on:
  release:
    types: [created, edited]
  schedule:
    - cron: '30 8 * * 1'
  discussion:
    types: [created, edited, pinned]
  issues:
    types: [opened, edited, reopened, closed]
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install howlongtobeatpy nose codecov
    - name: Test
      run: |
        nosetests howlongtobeatpy --with-coverage
        coverage xml
    - name: Upload Coverage codecov
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        codecov
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    
